name: Ci/CD Strava Tracking

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.14.0]

    steps:
      - uses: actions/checkout@v3
      - name: Build and Test
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn install

  deployment:
    runs-on: ubuntu-latest
    needs: build
    name: Deploy to EC2
    steps:
      - uses: actions/checkout@v3
      - name: Execute SSH commmands on remote server
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > keypair.pem && chmod 600 keypair.pem
          ssh -o StrictHostKeyChecking=no -i keypair.pem ${{ secrets.SSH_HOST }} '
          source ~/.nvm/nvm.sh && node -v
          bash deploy.sh'