name: ESLint check

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  eslint-check:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'yarn'
      - name: Install Node packages
        run: yarn install --registry=https://registry.yarnpkg.com/
      - name: Run ESLint
        run: yarn lint
